services: 
  tagging:
    image: image_tagging:0.7
    ports:
      - 3000:3000
    environment:
      - NUM_WORKERS=1
      - CPUS_PER_WORKER=8
      - BATCH_SIZE=100
      - BATCH_TIMEOUT=200000
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 20G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tagging-ui:
    build: tagging-ui
    ports:
      - 80:80
    environment:
      IMAGE_TAGGING_ENDPOINT: http://tagging:3000/predict
    

