version: '3.8'
services: 
  image_tagging:
    image: image_tagging:0.6
    ports:
      - 3000:3000
    environment:
      - NUM_WORKERS=1
      - CPUS_PER_WORKER=2
      - BATCH_SIZE=16
      # - ENABLE_GPU=1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

